name: Terraform Automation

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAYS2NTZMH2A6PELOI
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 4.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        if: github.event.pull_request.merged == true
        run: terraform apply -auto-approve
